name: emma_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  flutter_screenutil: ^3.2.0
  effective_dart: ^1.3.0
  #localization
  intl: ^0.16.1
  #bloc
  flutter_bloc: any
  #ui utils
  flutter_svg: ^0.19.0
  #other
  animated_rotation: ^1.0.0
  hive_flutter: ^0.3.0+2
  local_auth: ^0.6.3+4
  mask_text_input_formatter: ^1.1.0
  url_launcher: ^5.7.8
  connectivity: ^2.0.2
  path_provider: ^1.6.24
  flutter_email_sender: ^4.0.0
  #dev
  equatable: ^1.2.5
  flutter_slidable: ^0.5.7
  bot_toast: ^3.0.5
  image_picker: ^0.6.7+21
  optimized_gesture_detector: ^0.0.5
  flutter_keyboard_visibility: ^4.0.3
  simple_image_crop: ^1.0.0
  health: ^3.0.3 
  reorderables: ^0.3.2
  pdf: ^2.0.0
  printing: ^4.0.0
  get: ^3.24.0
  flutter_local_notifications: ^4.0.1
  rxdart: ^0.25.0
  flutter_keyboard_size: ^0.1.2+2
  keyboard_utils: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  built_value_generator: ^7.1.0
  build_runner: ^1.10.1

dependency_overrides:
  simple_image_crop: #https://github.com/lijungegea/flutter_simple_image_crop/pull/21
    git:
      url: https://github.com/lijungegea/flutter_simple_image_crop
      ref: bafd430

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/pdf_icons/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
 #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter_intl:
  enabled: true
  main_locale: ru
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

 
