name: emma_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^3.2.0
  effective_dart: ^1.3.0
  #built
  built_value: ^7.1.0
  built_collection: ^4.3.2
  #generator
  flutter_gen: ^1.2.1
  #di
  get_it: ^4.0.4
  injectable: any
  #logger
  logger: ^0.9.2
  device_preview: ^0.4.8
  #localization
  intl: ^0.16.1
  #bloc
  flutter_bloc: any
  #info
  package_info: any
  device_info: any
  #Image and Icons
  carousel_slider: ^2.3.1
  #dio
  dio_flutter_transformer: any
  dio_http_cache: any
  dio: 3.0.10
  #ui utils
  cached_network_image: ^2.3.2+1
  flushbar: ^1.10.4
  flutter_svg: ^0.19.0
  qr_flutter: ^3.2.0
  pinput: ^0.2.6
  webview_flutter: ^1.0.5
  lottie: ^0.7.0+1
  flutter_linkify: ^4.0.2
  #firebase
  # firebase_crashlytics: "^0.2.3+1"
  # firebase_core: ^0.5.2+1
  # firebase_analytics: ^6.2.0
  #other
  google_maps_cluster_manager: ^0.2.0
  google_maps_flutter: ^1.0.3
  animated_rotation: ^1.0.0
  geolocator: ^6.1.0
  hive_flutter: ^0.3.0+2
  local_auth: ^0.6.3+4
  mask_text_input_formatter: ^1.1.0
  url_launcher: ^5.7.8
  date_format: ^1.0.9
  crypto: ^2.1.5
  connectivity: ^2.0.2
  path_provider: ^1.6.24
  #dev
  mockito: any
  rxdart: ^0.24.1
  bottom_sheet: ^0.0.1-dev.5
  equatable: ^1.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.1.0
  build_runner: ^1.10.1
  pedantic: ^1.9.0
  hive_generator: ^0.7.0+2
  pretty_dio_logger: ^1.1.1
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
 #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter_gen:
  output: lib/generated/
  lineLength: 80

  integrations:
    flutter_svg: true
flutter_intl:
  enabled: true
  main_locale: ru
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

 
